### ISSUE TITLE
python -m diarize command does not work

### ISSUE THREAD

**Issue by Oheed911** [miguelvalente/whisperer#21]
when i have ran command `python -m main convert` command, it asks for sample rate. i passed the sample it started working and converted the files to .wav but when i ran the 2nd command `python -m diarize` it does not work. i also tried running it like `python -m main diarize` but it gives me segmentation fault.

**Comment by miguelvalente** [comment]
I thank you for filing an issue. I reverted some commits that should fix some stuff. Try pulling the repo and following the updated README. 

Could you let me know if the issue continues? The segmentation fault could be a lack of RAM on your machine, your audio files are too big. In that case, I'd advise you to cut them with some tool.

**Comment by gnmarten** [comment]
dunno if related, but I noticed that if you get the number of speakers wrong, the command may complete but without output. (e.g. music intro was singled out as separate speaker). Also, default language is set to Whisper model "base.en", adjust accordingly also in whisperer.py if not English.

**Comment by miguelvalente** [comment]
The diarizer model finds the speakers  unsupervised. I'll add an option to allow the designation of the number of speakers through some config file. But it requires the user to go through each file manually.

I'll also make it so that you can easily change between languages.

**Comment by miguelvalente** [comment]
stale.
