### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by gnmarten** [miguelvalente/whisperer#23]
Very fond of this concept, thanks, massive timesaver.

However, I ran into an error. fresh_cuts has the timestamps and the speakers, but then
```
speaker_embeds = embed(speakers_files[0], embedder)
```
leads to
```
----> 1 speaker_embeds = embed(speakers_files[0], embedder)
IndexError: list index out of range
```
When are the separate "audio_files_wav/speakers" supposed to be created? Because at this stage, they are not there yet, right?

Running TestDiarize.ipynb on Colab with Python 3.8 rather than Python 3.10 (wav file is about 20 minutes, one of the speakers is a bit muffled because in a Zoom call)

Any suggestions?

**Comment by miguelvalente** [comment]
Thanks 😄. Can you show me what your data directory looks like? Including any files that got generated. The "speakers/" dir gets populated at the ens of the diarization.

**Comment by gnmarten** [comment]
sorry, my bad, I assumed the notebook contained the whole pipeline, but I think it doesn't
I am now running the python commands rather than the notebook, now the directories are created in due order
works like a charm, this is splendid
just thinking about the hoops I had to jump through to arrive at the result earlier (transcribing twice in fact ...)
I expect this repository to receive a lot of stars!

**Comment by miguelvalente** [comment]
Thanks!
